version: "3"

services:
  #   backend:
  #     build: ./
  #     container_name: backend
  #     ports:
  #       - ${PORT}:${PORT}
  #     volumes:
  #       - ./src:/backend/src
  #     env_file:
  #       - .env
  #     depends_on:
  #       - mongo

  mongo:
    image: mongo:4.4.6
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_data: {}
